### ISSUE TITLE
Here's some Python to get the Swedish list

### ISSUE THREAD

**Issue by vaizki** [section42/hcert-trustlist-mirror#2]
I looked at the swedish endpoint, it was immediately obvious that it's a JWT so I made a python snippet to dump it in your format. Because I don't know the signing key used, the code does not verify the JWS signature at the end of the data.

https://gist.github.com/vaizki/3caf81dd105c712a1fe5d7117cd59d7b

I have access to the Finnish endpoint also but that one is a lot harder to automate.

**Comment by jnischler** [comment]
Hey, thanks for the contribution.
Feel free to create a PR for the finnish endpoint if you want to.

regards
Julian
