### ISSUE TITLE
IT trustlist

### ISSUE THREAD

**Issue by DanieleQ97** [section42/hcert-trustlist-mirror#7]
Hi there,
You can get Italian Ministry of Health's trustlist with this:
[https://github.com/ministero-salute/dcc-utils/blob/master/examples/fetch_certificates.js](https://github.com/ministero-salute/dcc-utils/blob/master/examples/fetch_certificates.js)

**Comment by DanieleQ97** [comment]
I'm working on it.
I was thinking of getting the script directly from their repository every time so that if they change something it will keep working without having to do anything.

**Comment by DanieleQ97** [comment]
Here it is
#10

**Comment by DanieleQ97** [comment]
It **should** work fine but there's definetely room for improvement

**Comment by jnischler** [comment]
thanks.
i have merged it.

could you please also update the readme file
and of course mention yourself 😉

thanks and regards
julian

**Comment by DanieleQ97** [comment]
Done #12

I've also added a link to the orignal forum thread and post that pointed me in the right direction

**Comment by jnischler** [comment]
Hey @DanieleQ97,

the was the italian trustlist moved ?
We have also seen new Certificates that require and api call to validate.

Regards
Julian

**Comment by jnischler** [comment]
We also found a revocation list:

https://get.dgc.gov.it/v1/dgc/settings

{
name: "black_list_uvci",
type: "black_list_uvci",
value: "URN:UVCI:01:FR:W7V2BE46QSBJ#L;URN:UVCI:01:FR:T5DWTJYS4ZR8#4;URN:UVCI:01DE/A80013335/TCXSI5Q08B0DIJGMIZJDF#T;URN:UVCI:01:PL:1/AF2AA5873FAF45DFA826B8A01237BDC4;01IT8523A6CADC834919A5214EA30779372D#1;01IT3DA01DD1A0AA4E4E92A10C11B04D39DB#8;01ITD85669BBC8E145FCA9CC83555B413952#3;01ITE901A12151934BAE92D7A537824BA260#3;01IT6E37CB3368F64C6884B3D2A74C266772#0;01ITC9E3B8B6B0344918AE7508E7094D9BCA#7;01ITB00C5897FF354FAFACFAFA391E613F59#8;01IT4C850BC31D3B41329A7EFC1F2AB5D2C5#2;01IT851F1A334C6B450DAD611A5DA4836404#6;01IT8658CD2A96F8435685D63B5C1DBC243F#5;01ITC78D2B44EA9D4C52A77C14C970676B62#9;URN:UVCI:01:PL:1/2A992C33754A4D379A7F61089485BB75;01IT757644969C3C4AC2B975AD9361F57BA0#2;01ITABF64E1EC2944E48A7EDC6AE13D7BCD1#4;01IT931C8B78D2274EFB813FEB0E7B65F004#0;01IT9F0432365FA44808BC4DAF64E0C9E841#4;01ITF70982F5EDA34F8AA56D52A9D4ED65E0#8;01ITB8C9FBDEC0284F72A46CED58E9D016D0#0;01IT9AD6DC2C22784F7990D19CE09951D738#4;01IT87E8E2C601FA49398C124163941F8C6B#4;01IT60072F78290F4EB1B3287B723A1B18C4#2;01ITBDE37E16689741E6A68C8BA31CD01328#5;01ITA413263CBA0446779A7E2BCD64332983#6;01ITB55EC0EDA986469DA83E07901DC8CD1B#6;01IT5864B7F7B0CC460C913FF7E78266EC97#1;01IT8C1CF98CF2324975AD8379D3FD89D8F0#8;01IT9BBE660A714E4C609A425972BCE03482#6;01IT74F90C75995648B68100630271E6D71D#0;01IT90A24E969B0C4D7BAF20088B5905ACDC#6;01IT4359EB33C508430CAF1035B22B5DB2B0#2;01IT2D21E4E677164B90A7FE82B227B4E38B#4;01IT7D62AB94C02F464A8C2E5D3AB2BD2F06#1;01IT6150418588334E95AF1EF26E69B4FAC4#1;01IT00930BEC68E742ED9954BB1C2E02199A#7;01IT48435EA7E9CD438398E7F84CBE263A0D#3;01IT6A8F8FB6AA184DE9864A912B49E06E95#5;01ITFF4D341DD8CB4D098C0381BC641C4BCE#7;01IT889BCA84BD7146ED993D54F6DF50AB01#7;01IT2FBCE050FF7C4D909272E3BBF8BA0E2F#1;01IT5E523B37B17E4A8B99BABC158EC20550#2;01ITA06867A22F9E4A7A991F0790AEAF2641#4;01ITA68306E9BE3449ADAD3E1D575D9C44E6#5;01IT386732303E8640C78E6373EAD5A8BC7A#4;01IT215C460F4CDB474680CCFADBE8DC1DF7#4;01IT1B65C6E35016458AA5A0D46C9406F2B3#3;01ITE94FA018EE2D4BF9BB47E4018E2582C9#2;01IT3F37002E698E4A6CB92F37D9E17D95B5#5;01IT66D81A9156D644FD8EE6058DDF14B55D#4;01ITE8161ACC484149A69CF8F139C57C8D89#2;01IT1C11CD43825D4AD2A8C5F99006DB14B4#7;01ITDA0E194CE5BF4530805BE8BB7E410529#9;01ITEAF1191644A045ED880309475C08867F#2;01ITA783073F498047F7A3A0E1B52C95C15D#6;01ITCEED207B160A4FACA85F09A1649EC53B#7;01IT6C9FEFADC8E64795B9C93CB82348E1C6#6;01ITD93252BAF918463782893F58F669D6B8#2;01ITCCC311AD9BF94604B9F30ADF8C6967F2#1;01ITE22D39C19DCD4E748CF8151292A13FA6#1;01IT4D3EA33C50884B9FBA5B042290AE27CA#5;01ITDF3AEAF9BD10448E8EA51D8FECBF405F#0;01IT07D91AD348744CAEA6D73A47B9681FFC#0;01ITBE8C0EA7FF014998AEC9D19344568DD5#8;01ITDF3D4D5EA4504C0098DC1E7B462B1827#9;01IT3530C2348BA04FD986F288E61AB50626#5;01IT3527B4A20078416EA648C2B222C6ABBE#3;01IT8ED9EA8837AE40CF9B7DFB0245BE9AE2#7;01IT9A054D66B6584EB8BFF862944ACE8B98#9;01IT014C363ADF6442879AA6D0761F6D52A5#0;01IT5AB1B28EA37149658205A22588EEB498#2;01ITD27BF56D0CC0472E941F9919F02DF3E1#0;01ITA366DD763B464FB78EC1701526D3337E#3;01ITC8D1B07B0E5B469292BE4797A66114D7#5;01IT0F34BD13BF4B44EEBA0B9A88306C5855#8;01ITF31612C404614E89AB7170D38D683DEF#4;01ITDECD2D94787A42E0BFED3CD098960713#6;01IT02CAA8E90137438C9F26297E010FAB47#4;01IT882AEF3B6A1640AB9FE1F3EF7E5B3BBA#0;01ITB5CAACD154E247DCBF16874B0E835ED5#1;01ITFBE4762A08BD422696EAE455D18FA12B#4;01IT8A97BFFAADED4A738B86E987AF01F5A0#7;01IT428D74EC192B4400B5D329130574CD0D#6;01IT97B5A4CA59E34A809AD576C8A2E8A07F#1;01IT50901B172DB1455E9DAE6443DBA9EA70#0;01ITB35CAE4FC49B4BF9BCE972421402E723#9;01IT2CA0F890192C4A3182F139475F74031A#7;01IT3A7B128F4C7048ADA3ACD824B2DE9D60#9;01IT08DE862C3C8A45B79BEFD39D5E2ACCEE#7;01ITF65CDA588FC1492CBA5B49E8A773E90F#8;01IT686C86782C634B16929096DE3C4DC136#7;01IT5722BE426BC745BD931941D7991F39AF#6;01IT1F11442A936C479695D2209294A1B838#5;01IT6BFE9CC387F44AADAB711AC99F9F4D9F#2;01IT3CAF17373BB445B7BE2AD7F21ECD4A2C#1;01IT632E84E3793D4F10BA3C7772AF7ED7AB#9;01ITFA033B83119849FD87B641E64EE7E2C5#2;01ITA1EA15DA6EA64D4AA0026A06C653B93A#0;01ITAA04EC0A7DD941CFA761E3B4525913BD#7;01IT39AA798644D94AE09C4E4CA3D77ED61A#4;01IT42B4154F212F442B9D257A8105F5ED8E#1;01IT71A2E6421CD4457EA7DCD802FE867957#7;01IT47BD1845F64A4D47808E027B9ADDE98E#9;01IT8106D979B209453F91D2E6E1919E196C#6;01IT79F5517C67C9452CA3C7A1D9882B1B07#0;01IT42F6B7956D894803B5E11125FE54A1A9#0;01IT92B071179515462682EFC16F8019EA24#7;01ITCAF42E82EB7545A182224D00A9322FB8#4;01IT4B3292222879475E93CCBDD49857BC29#6;01ITBBCB7FA03FA044F5B50970EB301037DB#9;01ITE15ECEC4260D45358F0FFC31C3E8DE2A#0;01IT864AFBB77EB447BEB150558515E61E29#4;01IT4B1D89A49D9143289CA26F1AA8A2CDCE#7;01ITA0C81DF2EA984DB79C0335E1902ADF24#1;01ITA2748B68033F4F3AADD703D0661BFEC2#2;01IT43D9907FDD244F63B5FB61008928B12B#3;01ITC26831E186434BC392BE318E60C0B234#6;01ITE026D9E45BBD4E6A99A9C531389FD752#0;01ITE965019D68C14808BDDE18006786FD5E#2;01IT86AA52829B7C43F5B7A8ADA7DE04992A#2;01IT9EA343581DAB4469831143AD233E731A#8;01IT6A4783D596EB4744B67F01675CA9DE69#6;01ITCD6AF553521E4B31AD003D0DA4C7EF6F#6;01IT7749640BD08048BAA06819FC85B9F594#0;01IT080B56B5ED5041DEA9FDCF42B7F7531F#6;01IT2EF80F9DBD104157B1A942C03B594EDB#5;01ITF579F07EAFD94676B05E78B5C90AB4B1#3;01ITF1744229CAF34106993D6DAE6FD789B6#1;01ITFF58F5ABC4DB497A8958B9361F931FD0#0;01ITEF6C40E5C4A9480892D1F980DA7BD5D9#9;01ITEED33E2F323F4EC8AB72FD32CF3D05F5#8;01IT7F05EB75145B4D748CFD3FC79CF0B293#9;01IT6123D87754A84C89A705F6FA9D9C1F23#7;"
},

**Comment by DanieleQ97** [comment]
I know there's something wrong with it as github has been spamming my mail
with failed actions for the past three days.

I have had a very busy week and barely had the time to acknowledge that
there is a proplem.
This evening I should've time to check what the problem is and try to fix it

I will message you as soon as I know what happened

Il ven 12 nov 2021, 12:33 Julian Nischler ***@***.***> ha
scritto:

**Comment by DanieleQ97** [comment]
Okay.
I've given it a look and it seem to be a problem with node dependecies (@peculiar/asn1-rsa).
The certificates haven't been moved and the script on health ministry's repo hasn't been changed so I think something has changed in the `@peculiar` code that made the new version incompatible with the script.
Probably downgrading the dependencies will fix the problem.

**Comment by DanieleQ97** [comment]
Probably my idea of getting the script from their repo every time and updating it on the fly to fit our needs was very bad from the beginning.
Maybe we should have our script based on theirs so that we can avoid all this mess with dependecies.

**Comment by DanieleQ97** [comment]
Got it. There is a problem with the dependencies of the dependencies.
`@peculiar/asn1-schema@2.0.44` broke something that was working with `@peculiar/asn1-schema@2.0.38` but npm thinks they are all valid dependencies for `@peculiar/x509@1.6.0` and that 2.0.44 better 'cause newer.

**Comment by DanieleQ97** [comment]
This should work for now: #13

**Comment by DanieleQ97** [comment]
As a long term solution we should probably write our own script to get the trustlist.
After all, their script was provided only as an example and fixing its dependecies is likely the last of their priorities.

I'm just a beginner with node.js so I'll probably start to draft up something in Python in my spare time.
I've previously tinkered with a bash script but that's obviously sub-optimal solution for this task, especially in the github action having to install lots of external tools.

Any "node.js-head" how wants to fix the original script or write a new one not requiring all that old/deprecated dependencies is more than welcome 😅

**Comment by jnischler** [comment]
okay i see thanks for the update
i think for now the PR is okay and we just need to keep monitoring the actions
